Frontend/food item card
katarzynagodlewska/verydeli pull request #15
Opened 2020-10-06 21:34 UTC by katarzynagodlewska

2020-10-06 22:13 UTC, KasperCisewski requested changes

2020-10-06 22:13 UTC, KasperCisewski commented on frontend/src/components/FoodItemCard.vue
> +
empty lines can be deleted

2020-10-07 08:08 UTC, katarzynagodlewska commented on frontend/src/components/FoodItemCard.vue
> +
done

2020-10-07 08:09 UTC, KasperCisewski approved these changes

2020-10-07 08:10 UTC, merged